let STATE={commands:[],schedules:[],settings:{},browser_tabs:[]};
const pageNames={overview:'Overview',school:'School Mode',browser:'Browser',chat:'Zoom Chat',commands:'Telegram Buttons',schedules:'Schedules',system:'System'};
const $=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1800)}
async function api(path,opt){const r=await fetch(path,opt||{});const text=await r.text();let data={};try{data=text?JSON.parse(text):{}}catch{}if(!r.ok)throw new Error(data.detail||data.message||text||('HTTP '+r.status));return data}
function go(page){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav .btn').forEach(x=>x.classList.remove('active'));$(page).classList.add('active');document.querySelector('[data-page="'+page+'"]')?.classList.add('active');$('pageTitle').textContent=pageNames[page]||page}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page));
async function refreshBrowserTabs(){try{const r=await api('/api/browser/tabs');STATE.browser_tabs=r.tabs||[];renderBrowserTabs()}catch(e){toast('Browser: '+e.message)}}
function toggleTabMenu(slot){const menu=document.getElementById('tab-menu-'+CSS.escape(slot));if(menu)menu.classList.toggle('show')}
async function focusTab(event,slot){event.stopPropagation();try{await api('/api/browser/focus/'+encodeURIComponent(slot),{method:'POST'});toast('Focused');await refreshBrowserTabs()}catch(e){toast('Focus failed: '+e.message)}}
async function closeTab(event,slot){event.stopPropagation();try{await api('/api/browser/close/'+encodeURIComponent(slot),{method:'POST'});toast('Closed');await refreshBrowserTabs();await refreshZoomChat()}catch(e){toast('Close failed: '+e.message)}}
function renderBrowserTabs(){const box=$('browserTabs');if(!box)return;box.innerHTML=STATE.browser_tabs.length?STATE.browser_tabs.map(t=>'<div class="item browser-tab" onclick="toggleTabMenu(\''+esc(t.slot)+'\')"><div><div class="item-title"><span class="tab-dot"></span>'+esc(t.title||t.slot)+'</div><div class="item-sub">'+esc(t.slot)+' • '+esc(t.url||'')+'</div></div><button class="btn">⋯</button><div id="tab-menu-'+esc(t.slot)+'" class="tab-menu"><button class="btn" onclick="focusTab(event,\''+esc(t.slot)+'\')">Focus</button><button class="btn danger" onclick="closeTab(event,\''+esc(t.slot)+'\')">Close</button></div></div>').join(''):'<div class="empty">No managed browser tabs are open.</div>'}
async function refreshZoomChat(){try{const r=await api('/api/browser/chat');if($('zoomChatState'))$('zoomChatState').textContent=r.open?'🟢 Zoom open':'⚪ No Zoom tab';if($('zoomChatMessages')){const messages=r.messages||[];$('zoomChatMessages').innerHTML=messages.length?messages.slice(-100).map(m=>'<div class="item"><div><div class="item-title">'+esc(m.text)+'</div><div class="item-sub">'+esc(m.time)+'</div></div></div>').join(''):'<div class="empty">No chat messages detected yet.</div>'}}catch(e){if($('zoomChatState'))$('zoomChatState').textContent='⚠️ '+e.message}}
async function reloadAll(){try{STATE=await api('/api/state');STATE.browser_tabs=STATE.browser_tabs||[];const s=STATE.settings;Object.entries({school_enabled:String(s.school_enabled),school_time:s.school_time,zoom_time:s.zoom_time,school_days:s.school_days.join(','),zoom_url:s.zoom_url,schoology_url:s.schoology_url,schoology_user:s.schoology_user,browser:s.browser,browser_profile:s.browser_profile}).forEach(([k,v])=>$(k).value=v);$('status').textContent='Ready';$('overviewSchool').innerHTML='<b>'+ (s.school_enabled?'ON':'OFF')+'</b> • '+esc(s.school_time)+' → '+esc(s.zoom_time)+' • '+esc(s.school_days.join(', '));$('overviewZoom').textContent=s.zoom_url||'—';$('overviewSchoology').textContent=s.schoology_url||'—';$('overviewPc').textContent='Host control available';$('overviewStats').textContent=STATE.commands.length+' buttons • '+STATE.schedules.length+' schedules';$('systemInfo').textContent='Brave: '+s.browser+' • Profile: '+s.browser_profile;renderCommands();renderSchedules();renderCommandSelect();renderBrowserTabs();if(!$('actionBuilder').children.length)addAction()}catch(e){$('status').textContent='Error';toast(e.message)}}
async function saveSettings(){try{const s=STATE.settings;const body={...s,school_enabled:$('school_enabled').value==='true',school_time:$('school_time').value,zoom_time:$('zoom_time').value,school_days:$('school_days').value.split(',').map(v=>Number(v.trim())).filter(Number.isInteger),zoom_url:$('zoom_url').value,schoology_url:$('schoology_url').value,schoology_user:$('schoology_user').value,browser:$('browser').value,browser_profile:$('browser_profile').value,schoology_password:$('schoology_password').value,pc_unlock_password:$('pc_unlock_password').value};await api('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});$('schoology_password').value='';$('pc_unlock_password').value='';toast('Saved');await reloadAll()}catch(e){toast('Save failed: '+e.message)}}
function addAction(data={type:'open_url'}){const wrap=document.createElement('div');wrap.className='action-row';wrap.innerHTML='<select><option value="open_url">Open URL</option><option value="open_zoom">Zoom</option><option value="open_schoology">LAUSD</option><option value="key">Key combo</option><option value="type">Type text</option></select><input placeholder="URL / keys / text"><button class="btn danger">Remove</button>';const sel=wrap.children[0],input=wrap.children[1];sel.value=data.type||'open_url';if(data.type==='open_url')input.value=data.url||'';if(data.type==='key')input.value=(data.combo||[]).join('+');if(data.type==='type')input.value=data.text||'';sel.onchange=()=>{input.placeholder=sel.value==='key'?'CTRL+L':sel.value==='type'?'Text':'URL'};wrap.children[2].onclick=()=>wrap.remove();$('actionBuilder').appendChild(wrap)}
function collectActions(){return [...$('actionBuilder').children].map(r=>{const type=r.children[0].value,v=r.children[1].value;return type==='open_url'?{type,url:v}:type==='key'?{type,combo:v.split('+').map(x=>x.trim().toUpperCase()).filter(Boolean)}:type==='type'?{type,text:v}:{type}})}
async function saveCommand(){try{const id=$('cmd_id').value.trim(),title=$('cmd_title').value.trim();if(!id||!title)return toast('Enter ID and title');const content=JSON.stringify({commands:[{id,title,actions:collectActions()}]});await api('/api/commands',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content})});toast('Button saved');clearCommand();await reloadAll()}catch(e){toast('Save failed: '+e.message)}}
function clearCommand(){$('cmd_id').value='';$('cmd_title').value='';$('actionBuilder').innerHTML='';addAction()}
function renderCommands(){$('commandsList').innerHTML=STATE.commands.length?STATE.commands.map(c=>'<div class="item"><div><div class="item-title">'+esc(c.title)+'</div><div class="item-sub">'+esc(c.id)+' • '+c.actions.length+' action(s)</div></div><div class="row"><button class="btn" onclick="runCmd(\''+esc(c.id)+'\')">Run</button><button class="btn danger" onclick="delCmd(\''+esc(c.id)+'\')">Delete</button></div></div>').join(''):'<div class="empty">No Telegram buttons yet.</div>'}
async function runCmd(id){try{await api('/api/commands/'+encodeURIComponent(id)+'/run',{method:'POST'});toast('Command sent')}catch(e){toast('Run failed: '+e.message)}}async function delCmd(id){try{await api('/api/commands/'+encodeURIComponent(id),{method:'DELETE'});toast('Removed');await reloadAll()}catch(e){toast('Delete failed: '+e.message)}}
function renderCommandSelect(){$('sch_command').innerHTML=STATE.commands.map(c=>'<option value="'+esc(c.id)+'">'+esc(c.title)+'</option>').join('')}
async function saveSchedule(){try{const body={id:$('sch_id').value.trim(),title:$('sch_title').value.trim(),time:$('sch_time').value.trim(),days:$('sch_days').value.split(',').map(v=>Number(v.trim())).filter(Number.isInteger),command_id:$('sch_command').value,enabled:$('sch_enabled').value==='true'};await api('/api/schedules',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});toast('Schedule saved');clearSchedule();await reloadAll()}catch(e){toast('Save failed: '+e.message)}}
function clearSchedule(){$('sch_id').value='';$('sch_title').value='';$('sch_time').value='';$('sch_days').value='0,1,2,3,4'}
function renderSchedules(){$('scheduleList').innerHTML=STATE.schedules.length?STATE.schedules.map(s=>'<div class="item"><div><div class="item-title">'+esc(s.title)+'</div><div class="item-sub">'+esc(s.time)+' • '+esc(s.days.join(', '))+' • '+esc(s.command_id)+'</div></div><button class="btn danger" onclick="delSch(\''+esc(s.id)+'\')">Delete</button></div>').join(''):'<div class="empty">No schedules yet.</div>'}
async function delSch(id){try{await api('/api/schedules/'+encodeURIComponent(id),{method:'DELETE'});toast('Removed');await reloadAll()}catch(e){toast('Delete failed: '+e.message)}}
async function runAgent(action){try{const r=await api('/api/action/'+action,{method:'POST'});toast(r.success?'Done':'Action completed')}catch(e){toast('Action failed')}}
async function runNamed(id){const c=STATE.commands.find(x=>x.id===id);if(c)await runCmd(id);else toast('Command not installed')}
$('command_file').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{await api('/api/commands',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content:await f.text()})});toast('Imported');await reloadAll()}catch(err){toast(err.message)}e.target.value=''})
reloadAll();
refreshBrowserTabs();
refreshZoomChat();
setInterval(refreshBrowserTabs,2000);
setInterval(refreshZoomChat,2000);